name: MSVC build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: microsoft/setup-msbuild@v2

    - name: Build x64
      run: |
        mkdir out && cd out
        cmake -G "Visual Studio 17 2022" -A x64 ..
        msbuild aitaonmatalin.sln /p:Platform=x64 /p:Configuration=Release /m

    - name: Print Hashes
      shell: pwsh
      run: |
        Get-ChildItem "out/bin/Release/*.exe" | Get-FileHash -Algorithm SHA256 | Format-List | Tee-Object hashes.txt

    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@v1.2.1"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Automated release (latest commit)"
          files: |
            hashes.txt
            out/bin/Release/*.exe
